### ISSUE TITLE
Группировка файлов лога

### ISSUE THREAD

**Issue by MiXaLiN17** [intensa/intensa.logger#9]
Привет!
При логировании определенных задач, необходимо как то формировать данные логи в отдельной директории. 
Будет ли в модуле такое?
По типу передачи определенного шаблона?
`$logger = new \Intensa\Logger\ILog('group_folder\logname');`
Или отдельного метода у класса ILog?

**Comment by IvanShishkin** [comment]
Привет. 
Да, такого функционала сейчас нет.
Планируется сделать метод setLogDirectory(string 'additional_dir').
Метод принимает название дополнительной директории. При вызове такого логера лог файлы будут попадать в дополнительную директорию (/logs/2021-12-10/additional_dir/file.log).

**Comment by IvanShishkin** [comment]
Добавлена возможность устанавливать дополнительную директорию для хранения логов через конструктор класса. 
`
$logger = new \Intensa\Logger\ILog('file', 'additional_dir');
$logger->log('mgs', []);
`
При таком вызове лог файл будет располагаться в директории /logs/2021-12-10/additional_dir/file.log
